<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Rukmangathan" failures="0" tests="2" name="com.testng.org.Timeout" time="3.042" errors="1" timestamp="2021-05-15T22:43:56 IST" skipped="0">
  <testcase classname="com.testng.org.Timeout" name="searchmob" time="0.006"/>
  <testcase classname="com.testng.org.Timeout" name="searchlaptop" time="3.036">
    <error message="Method com.testng.org.Timeout.searchlaptop() didn&#039;t finish within the time-out 3000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.org.Timeout.searchlaptop() didn't finish within the time-out 3000
at java.base@15.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:269)
at java.base@15.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base@15.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base@15.0.2/java.lang.Thread.run(Thread.java:832)
]]>
    </error>
  </testcase> <!-- searchlaptop -->
</testsuite> <!-- com.testng.org.Timeout -->
